import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import MainNavigation from "@/layout/main-navigation";
import React from "react";
import Message from "@/components/message";
import {ChakraProvider} from "@chakra-ui/react";
import Footer from "@/layout/footer";

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next global',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <>
          <MainNavigation />
              <Message/>
            {children}
          <Footer/>
      </>
  )
}
